name: Deploy migrations to prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push migrations to production db
        run: |
          supabase link --project-ref $MIRAMAR_PROD_PROJECT_ID
          supabase db push

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
  MIRAMAR_PROD_PROJECT_ID: ${{ secrets.MIRAMAR_PROD_PROJECT_ID }}